generatorName: go

gitHost: github.com
gitUserId: sherweb
gitRepoId: go-netbox/v4

packageName: netbox

globalProperties:
  apiDocs: "false"
  modelDocs: "false"
  apiTests: "false"
  modelTests: "false"

additionalProperties:
  disallowAdditionalPropertiesIfNotPresent: "false"
  generateInterfaces: "true"
  isGoSubmodule: "true"
  packageName: "netbox"
  packageVersion: "4"
  useDefaultValuesForRequiredVars: "true"
  enumClassPrefix: "true"
